[package]
name = "dispipe"
version = "0.1.0"
authors = ["jnlon <jnlon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
nix = "0.17.0"
rust-ini = "0.15.3"
